#pragma once

#define ANM_FILE_TEXT 0

#define ANM_FILE_ASCII_0 1
#define ANM_FILE_ASCII_1 2
#define ANM_FILE_ASCII_2 3
#define ANM_FILE_ASCII ANM_FILE_ASCII_0

#define ANM_FILE_CAPTURE 4
#define ANM_FILE_STAGE_BG1 5
#define ANM_FILE_STAGE_BG2 6
#define ANM_FILE_STAGE_BG3 7
#define ANM_FILE_STAGE_BG4 8
#define ANM_FILE_STAGE_BG5 9
#define ANM_FILE_PLAYER 10

#define ANM_FILE_BULLETS_0 11
#define ANM_FILE_BULLETS_1 12
#define ANM_FILE_BULLETS_2 13
#define ANM_FILE_BULLETS_3 14
#define ANM_FILE_BULLETS ANM_FILE_BULLETS_0

#define ANM_FILE_ENEMY 15
#define ANM_FILE_ENEMY2 16
#define ANM_FILE_EFFECTS 17
#define ANM_FILE_EFFECTS2 18

#define ANM_FILE_EFFECTS3_0 19
#define ANM_FILE_EFFECTS3_1 20
#define ANM_FILE_EFFECTS3 ANM_FILE_EFFECTS3_0

#define ANM_FILE_FRONT_0 21
#define ANM_FILE_FRONT_1 22
#define ANM_FILE_FRONT ANM_FILE_FRONT_0

#define ANM_FILE_LOADING 23
#define ANM_FILE_STAGE_TEXT 24

#define ANM_FILE_FACE_0 25
#define ANM_FILE_FACE_1 26
#define ANM_FILE_FACE_2 27
#define ANM_FILE_FACE ANM_FILE_FACE_0

#define ANM_FILE_FACE_STAGE_0 28
#define ANM_FILE_FACE_STAGE_1 29
#define ANM_FILE_FACE_STAGE_2 30
#define ANM_FILE_FACE_STAGE_3 31
#define ANM_FILE_FACE_STAGE ANM_FILE_FACE_STAGE_0

#define ANM_FILE_TITLE_0 32
#define ANM_FILE_TITLE_1 33
#define ANM_FILE_TITLE_2 34
#define ANM_FILE_TITLE_3 35
#define ANM_FILE_TITLE_4 36
#define ANM_FILE_TITLE_5 37
#define ANM_FILE_TITLE_6 38
#define ANM_FILE_TITLE_7 39
#define ANM_FILE_TITLE_8 40
#define ANM_FILE_TITLE_9 41
#define ANM_FILE_TITLE ANM_FILE_TITLE_0

#define ANM_FILE_RESULT_0 42
#define ANM_FILE_RESULT_1 43
#define ANM_FILE_RESULT_2 44
#define ANM_FILE_RESULT_3 45
#define ANM_FILE_RESULT ANM_FILE_RESULT_0

#define ANM_FILE_MUSIC_0 46
#define ANM_FILE_MUSIC_1 47
#define ANM_FILE_MUSIC ANM_FILE_MUSIC_0

#define ANM_FILE_STAFF 49

#define ANM_OFFSET_ASCII 0x000
#define ANM_OFFSET_BULLETS 0x200
#define ANM_OFFSET_EFFECTS 0x2dc
#define ANM_OFFSET_EFFECTS2 0x2dd
#define ANM_OFFSET_EFFECTS3 0x2de
#define ANM_OFFSET_STAGE_BG1 0x300
#define ANM_OFFSET_STAGE_BG2 0x310
#define ANM_OFFSET_STAGE_BG3 0x320
#define ANM_OFFSET_STAGE_BG4 0x330
#define ANM_OFFSET_STAGE_BG5 0x340
#define ANM_OFFSET_PLAYER 0x400
#define ANM_OFFSET_FACE 0x4a0
#define ANM_OFFSET_FACE_STAGE 0x4ad
#define ANM_OFFSET_FRONT 0x600
#define ANM_OFFSET_STAFF 0x600
#define ANM_OFFSET_LOADING 0x61e
#define ANM_OFFSET_TEXT 0x700
#define ANM_OFFSET_CAPTURE 0x724
#define ANM_OFFSET_MENU_BG 0x724
#define ANM_OFFSET_STAGE_TEXT 0x800
#define ANM_OFFSET_TITLE 0x900
#define ANM_OFFSET_MUSIC 0x900
#define ANM_OFFSET_RESULT 0x900
#define ANM_OFFSET_ENEMY 0x900

#define ANM_SCRIPT_ASCII_ENEMY_SPELLCARD_NAME_BG (ANM_OFFSET_ASCII + 0)
#define ANM_SCRIPT_ASCII_SPELLCARD_NAME_BG (ANM_OFFSET_ASCII + 1)
#define ANM_SCRIPT_ASCII_SPELLCARD_BONUS (ANM_OFFSET_ASCII + 2)
#define ANM_SCRIPT_ASCII_DIGIT (ANM_OFFSET_ASCII + 3)
#define ANM_SCRIPT_ASCII_CHERRY_GAUGE (ANM_OFFSET_ASCII + 4)
#define ANM_SCRIPT_ASCII_CHERRY_BORDER (ANM_OFFSET_ASCII + 5)
#define ANM_SCRIPT_ASCII_BOSS_MARKER (ANM_OFFSET_ASCII + 6)
#define ANM_SCRIPT_ASCII_DEMO_MARKER (ANM_OFFSET_ASCII + 7)
#define ANM_SCRIPT_ASCII_PAUSE_MENU (ANM_OFFSET_ASCII + 254)
#define ANM_SCRIPT_ASCII_RETRY_MENU (ANM_OFFSET_ASCII + 264)
#define ANM_SCRIPT_ASCII_RETRY_MENU_LIVES (ANM_OFFSET_ASCII + 268)

#define ANM_SPRITE_ASCII_LARGE_FONT (ANM_OFFSET_ASCII + 0)
#define ANM_SPRITE_ASCII_SMALL_SCORE (ANM_OFFSET_ASCII + 32)
#define ANM_SPRITE_ASCII_DIGITS (ANM_OFFSET_ASCII + 132)
#define ANM_SPRITE_ASCII_RETRY_MENU_LIVES (ANM_OFFSET_ASCII + 262)
#define ANM_SPRITE_ASCII_LOADING (ANM_OFFSET_ASCII + 268)
#define ANM_SPRITE_ASCII_PAUSE_MENU_DIFFICULTY (ANM_OFFSET_ASCII + 269)

#define ANM_SCRIPT_BULLETS_PELLET (ANM_OFFSET_BULLETS + 0)
#define ANM_SCRIPT_BULLETS_RING_BALL (ANM_OFFSET_BULLETS + 1)
#define ANM_SCRIPT_BULLETS_RICE (ANM_OFFSET_BULLETS + 2)
#define ANM_SCRIPT_BULLETS_BALL (ANM_OFFSET_BULLETS + 3)
#define ANM_SCRIPT_BULLETS_KUNAI (ANM_OFFSET_BULLETS + 4)
#define ANM_SCRIPT_BULLETS_SHARD (ANM_OFFSET_BULLETS + 5)
#define ANM_SCRIPT_BULLETS_ARROWHEAD (ANM_OFFSET_BULLETS + 6)
#define ANM_SCRIPT_BULLETS_BIG_BALL (ANM_OFFSET_BULLETS + 7)
#define ANM_SCRIPT_BULLETS_BUTTERFLY (ANM_OFFSET_BULLETS + 8)
#define ANM_SCRIPT_BULLETS_KNIFE (ANM_OFFSET_BULLETS + 9)
#define ANM_SCRIPT_BULLETS_LASER (ANM_OFFSET_BULLETS + 10)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_SMALL (ANM_OFFSET_BULLETS + 15)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_MEDIUM (ANM_OFFSET_BULLETS + 16)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_BIG (ANM_OFFSET_BULLETS + 17)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_FAST (ANM_OFFSET_BULLETS + 18)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_NORMAL (ANM_OFFSET_BULLETS + 19)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_SLOW (ANM_OFFSET_BULLETS + 20)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_FAST (ANM_OFFSET_BULLETS + 21)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_NORMAL (ANM_OFFSET_BULLETS + 22)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_SLOW (ANM_OFFSET_BULLETS + 23)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_HUGE (ANM_OFFSET_BULLETS + 24)
#define ANM_SCRIPT_BULLETS_BUBBLE (ANM_OFFSET_BULLETS + 168)
#define ANM_SCRIPT_BULLETS_BUBBLE_SPAWN_NORMAL (ANM_OFFSET_BULLETS + 169)
#define ANM_SCRIPT_BULLETS_BUBBLE_SPAWN_SLOW (ANM_OFFSET_BULLETS + 170)
#define ANM_SCRIPT_BULLETS_ITEM_SPAWN_ARRAY (ANM_OFFSET_BULLETS + 196)
#define ANM_SCRIPT_BULLETS_ITEM_DESPAWN (ANM_OFFSET_BULLETS + 203)

#define ANM_SPRITE_BULLETS_ARROWHEAD (ANM_OFFSET_BULLETS + 96)
#define ANM_SPRITE_BULLETS_ARROWHEAD_WHITE (ANM_OFFSET_BULLETS + 111)
#define ANM_SPRITE_BULLETS_BUTTERFLY (ANM_OFFSET_BULLETS + 120)
#define ANM_SPRITE_BULLETS_BUTTERFLY_LBLUE (ANM_OFFSET_BULLETS + 124)
#define ANM_SPRITE_BULLETS_BUTTERFLY_WHITE (ANM_OFFSET_BULLETS + 127)
#define ANM_SPRITE_BULLETS_ORB (ANM_OFFSET_BULLETS + 146)
#define ANM_SPRITE_BULLETS_ITEMS_OFFSCREEN_ARRAY (ANM_OFFSET_BULLETS + 172)
#define ANM_SPRITE_BULLETS_ITEMS_ARRAY (ANM_OFFSET_BULLETS + 182)
#define ANM_SPRITE_BULLETS_CHERRY_PETAL (ANM_OFFSET_BULLETS + 216)

#define ANM_SCRIPT_EFFECTS_SPELLCARD_ARRAY (ANM_OFFSET_EFFECTS + 0)

#define ANM_SCRIPT_PLAYER_IDLE (ANM_OFFSET_PLAYER + 0)
#define ANM_SCRIPT_PLAYER_MOVING_LEFT (ANM_OFFSET_PLAYER + 1)
#define ANM_SCRIPT_PLAYER_STOPPING_LEFT (ANM_OFFSET_PLAYER + 2)
#define ANM_SCRIPT_PLAYER_MOVING_RIGHT (ANM_OFFSET_PLAYER + 3)
#define ANM_SCRIPT_PLAYER_STOPPING_RIGHT (ANM_OFFSET_PLAYER + 4)
#define ANM_SCRIPT_PLAYER_OPTION_LEFT (ANM_OFFSET_PLAYER + 128)
#define ANM_SCRIPT_PLAYER_OPTION_RIGHT (ANM_OFFSET_PLAYER + 129)
#define ANM_SCRIPT_PLAYER_REIMU_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 133)
#define ANM_SCRIPT_PLAYER_REIMU_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 137)
#define ANM_SCRIPT_PLAYER_REIMU_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 141)
#define ANM_SCRIPT_PLAYER_MARISA_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 5)
#define ANM_SCRIPT_PLAYER_MARISA_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 12)
#define ANM_SCRIPT_PLAYER_MARISA_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 8)
#define ANM_SCRIPT_PLAYER_SAKUYA_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 5)
#define ANM_SCRIPT_PLAYER_SAKUYA_A_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 7)
#define ANM_SCRIPT_PLAYER_SAKUYA_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 9)
#define ANM_SCRIPT_PLAYER_SAKUYA_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 13)

#define ANM_SCRIPT_FACE_PORTRAIT_SHOW_LEFT (ANM_OFFSET_FACE + 0)
#define ANM_SCRIPT_FACE_SPELLCARD_PORTRAIT (ANM_OFFSET_FACE + 1)
#define ANM_SCRIPT_FACE_PORTRAIT_SHOW_RIGHT (ANM_OFFSET_FACE + 2)
#define ANM_SCRIPT_FACE_ENEMY_SPELLCARD_PORTRAIT (ANM_OFFSET_FACE + 3)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_LEFT (ANM_OFFSET_FACE + 4)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_UP (ANM_OFFSET_FACE + 5)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_RIGHT (ANM_OFFSET_FACE + 6)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_DOWN (ANM_OFFSET_FACE + 7)

#define ANM_SPRITE_FACE_PORTRAIT_ARRAY (ANM_OFFSET_FACE + 0)
#define ANM_SPRITE_FACE_SPELLCARD_DECOR (ANM_OFFSET_FACE + 12)

#define ANM_SPRITE_FACE_STAGE_ENEMY_PORTRAIT_ARRAY (ANM_OFFSET_FACE_STAGE + 0)
#define ANM_SPRITE_FACE_STAGE_ENEMY_SPELLCARD_PORTRAIT_ARRAY (ANM_OFFSET_FACE_STAGE + 0)

#define ANM_SCRIPT_FRONT_UI_ELEMENTS_ARRAY (ANM_OFFSET_FRONT + 0)

#define ANM_SPRITE_FRONT_ENEMY_NAME_FRAME (ANM_OFFSET_FRONT + 9)
#define ANM_SPRITE_FRONT_ENEMY_NAME (ANM_OFFSET_FRONT + 14)

#define ANM_SCRIPT_LOADING_STAGE_CLEAR_BG (ANM_OFFSET_LOADING + 0)

#define ANM_SCRIPT_TEXT_DIALOGUE (ANM_OFFSET_TEXT + 0)
#define ANM_SCRIPT_TEXT_INTRO (ANM_OFFSET_TEXT + 2)
#define ANM_SCRIPT_TEXT_SPELLCARD_NAME (ANM_OFFSET_TEXT + 4)
#define ANM_SCRIPT_TEXT_ENEMY_SPELLCARD_NAME (ANM_OFFSET_TEXT + 5)
#define ANM_SCRIPT_TEXT_MAINMENU_OPTION_DESC (ANM_OFFSET_TEXT + 6)
#define ANM_SCRIPT_TEXT_MUSIC_DESC (ANM_OFFSET_TEXT + 7)
#define ANM_SCRIPT_TEXT_ENDING (ANM_OFFSET_TEXT + 15)
#define ANM_SCRIPT_TEXT_SPELLCARD_LIST_ARRAY (ANM_OFFSET_TEXT + 21)

#define ANM_SCRIPT_CAPTURE_TRANSITION_SNAPSHOT (ANM_OFFSET_CAPTURE + 1)
#define ANM_SCRIPT_CAPTURE_TRANSITION_QUAD_ARRAY (ANM_OFFSET_CAPTURE + 2)

#define ANM_SCRIPT_STAGE_TEXT (ANM_OFFSET_STAGE_TEXT + 0)
#define ANM_SCRIPT_STAGE_TEXT_MUSIC (ANM_OFFSET_STAGE_TEXT + 4)
#define ANM_SCRIPT_STAGE_TEXT_MUSIC_ST6 (ANM_OFFSET_STAGE_TEXT + 5)

#define ANM_SPRITE_STAGE_TEXT_MUSIC (ANM_OFFSET_STAGE_TEXT + 3)

#define ANM_SCRIPT_MUSIC (ANM_OFFSET_MUSIC + 0)
#define ANM_SCRIPT_MUSIC_TITLE (ANM_OFFSET_MUSIC + 1)

#define ANM_SCRIPT_RESULT_ARRAY (ANM_OFFSET_RESULT + 0)

#define ANM_SPRITE_RESULT_SPELLCARD_BAR (ANM_OFFSET_RESULT + 16)

#define ANM_SCRIPT_ENEMY_ARRAY (ANM_OFFSET_ENEMY + 0)
