#pragma once

// In comparison to th06, anm files in th07 may have multiple entries. If an
// anm file contains multiple entries, those entries are distinguished with
// an _n where n is the nth entry in that anm file.

#define ANM_FILE_TEXT 0

#define ANM_FILE_ASCII_0 1
#define ANM_FILE_ASCII_1 2
#define ANM_FILE_ASCII_2 3
#define ANM_FILE_ASCII ANM_FILE_ASCII_0

#define ANM_FILE_CAPTURE 4
#define ANM_FILE_STAGE_BG 5
#define ANM_FILE_STAGE4_BG2 6
#define ANM_FILE_STAGE4_BG3 7
#define ANM_FILE_STAGE4_BG4 8
#define ANM_FILE_STAGE4_BG5 9
#define ANM_FILE_PLAYER 10

#define ANM_FILE_BULLETS_0 11
#define ANM_FILE_BULLETS_1 12
#define ANM_FILE_BULLETS_2 13
#define ANM_FILE_BULLETS_3 14
#define ANM_FILE_BULLETS ANM_FILE_BULLETS_0

#define ANM_FILE_ENEMY 15
#define ANM_FILE_ENEMY2 16
#define ANM_FILE_EFFECTS 17
#define ANM_FILE_EFFECTS2 18

#define ANM_FILE_EFFECTS3_0 19
#define ANM_FILE_EFFECTS3_1 20
#define ANM_FILE_EFFECTS3 ANM_FILE_EFFECTS3_0

#define ANM_FILE_FRONT_0 21
#define ANM_FILE_FRONT_1 22
#define ANM_FILE_FRONT ANM_FILE_FRONT_0

#define ANM_FILE_LOADING 23
#define ANM_FILE_STAGE_TEXT 24

#define ANM_FILE_FACE_0 25
#define ANM_FILE_FACE_1 26
#define ANM_FILE_FACE_2 27
#define ANM_FILE_FACE ANM_FILE_FACE_0

#define ANM_FILE_FACE_STAGE_0 28
#define ANM_FILE_FACE_STAGE_1 29
#define ANM_FILE_FACE_STAGE_2 30
#define ANM_FILE_FACE_STAGE_3 31
#define ANM_FILE_FACE_STAGE ANM_FILE_FACE_STAGE_0

#define ANM_FILE_TITLE_0 32
#define ANM_FILE_TITLE_1 33
#define ANM_FILE_TITLE_2 34
#define ANM_FILE_TITLE_3 35
#define ANM_FILE_TITLE_4 36
#define ANM_FILE_TITLE_5 37
#define ANM_FILE_TITLE_6 38
#define ANM_FILE_TITLE_7 39
#define ANM_FILE_TITLE_8 40
#define ANM_FILE_TITLE_9 41
#define ANM_FILE_TITLE ANM_FILE_TITLE_0

#define ANM_FILE_RESULT_0 42
#define ANM_FILE_RESULT_1 43
#define ANM_FILE_RESULT_2 44
#define ANM_FILE_RESULT_3 45
#define ANM_FILE_RESULT ANM_FILE_RESULT_0

#define ANM_FILE_MUSIC_0 46
#define ANM_FILE_MUSIC_1 47
#define ANM_FILE_MUSIC ANM_FILE_MUSIC_0

#define ANM_FILE_STAFF 49

#define ANM_OFFSET_ASCII_0 0x000
#define ANM_OFFSET_ASCII_1 0x092
#define ANM_OFFSET_ASCII_2 0x0fe
#define ANM_OFFSET_ASCII ANM_OFFSET_ASCII_0

#define ANM_OFFSET_BULLETS_0 0x200
#define ANM_OFFSET_BULLETS_1 0x2a8
#define ANM_OFFSET_BULLETS_2 0x2da
#define ANM_OFFSET_BULLETS_3 0x2db
#define ANM_OFFSET_BULLETS ANM_OFFSET_BULLETS_0

#define ANM_OFFSET_EFFECTS 0x2dc
#define ANM_OFFSET_EFFECTS2 0x2dd

#define ANM_OFFSET_EFFECTS3_0 0x2de
#define ANM_OFFSET_EFFECTS3_1 0x2e0
#define ANM_OFFSET_EFFECTS3_2 0x2e2
#define ANM_OFFSET_EFFECTS3 ANM_OFFSET_EFFECTS3_0

#define ANM_OFFSET_STAGE_BG 0x300
#define ANM_OFFSET_STAGE4_BG2 0x310
#define ANM_OFFSET_STAGE4_BG3 0x320
#define ANM_OFFSET_STAGE4_BG4 0x330
#define ANM_OFFSET_STAGE4_BG5 0x340
#define ANM_OFFSET_PLAYER 0x400

#define ANM_OFFSET_FACE_0 0x4a0
#define ANM_OFFSET_FACE_1 0x4a8
#define ANM_OFFSET_FACE ANM_OFFSET_FACE_0

#define ANM_OFFSET_FACE_STAGE 0x4ad

#define ANM_OFFSET_FRONT_0 0x600
#define ANM_OFFSET_FRONT_1 0x60e
#define ANM_OFFSET_FRONT ANM_OFFSET_FRONT_0

#define ANM_OFFSET_STAFF 0x600
#define ANM_OFFSET_LOADING 0x61e
#define ANM_OFFSET_TEXT 0x700
#define ANM_OFFSET_CAPTURE 0x724
#define ANM_OFFSET_MENU_BG 0x724
#define ANM_OFFSET_STAGE_TEXT 0x800

#define ANM_OFFSET_TITLE_0 0x900
#define ANM_OFFSET_TITLE_1 0x901
#define ANM_OFFSET_TITLE_2 0x95f
#define ANM_OFFSET_TITLE_3 0x96a
#define ANM_OFFSET_TITLE_4 0x96f
#define ANM_OFFSET_TITLE_5 0x974
#define ANM_OFFSET_TITLE_6 0x979
#define ANM_OFFSET_TITLE_7 0x97f
#define ANM_OFFSET_TITLE_8 0x984
#define ANM_OFFSET_TITLE_9 0x9a1
#define ANM_OFFSET_TITLE ANM_OFFSET_TITLE_0

#define ANM_OFFSET_MUSIC_0 0x900
#define ANM_OFFSET_MUSIC_1 0x901
#define ANM_OFFSET_MUSIC ANM_OFFSET_MUSIC_0

#define ANM_OFFSET_RESULT_0 0x900
#define ANM_OFFSET_RESULT_1 0x909
#define ANM_OFFSET_RESULT_2 0x911
#define ANM_OFFSET_RESULT_3 0x928
#define ANM_OFFSET_RESULT ANM_OFFSET_RESULT_0

#define ANM_OFFSET_ENEMY 0x900

#define ANM_SCRIPT_ASCII_ENEMY_SPELLCARD_NAME_BG (ANM_OFFSET_ASCII_0 + 0)
#define ANM_SCRIPT_ASCII_SPELLCARD_NAME_BG (ANM_OFFSET_ASCII_0 + 1)
#define ANM_SCRIPT_ASCII_SPELLCARD_BONUS (ANM_OFFSET_ASCII_0 + 2)
#define ANM_SCRIPT_ASCII_DIGIT (ANM_OFFSET_ASCII_0 + 3)
#define ANM_SCRIPT_ASCII_CHERRY_GAUGE (ANM_OFFSET_ASCII_0 + 4)
#define ANM_SCRIPT_ASCII_CHERRY_BORDER (ANM_OFFSET_ASCII_0 + 5)
#define ANM_SCRIPT_ASCII_BOSS_MARKER (ANM_OFFSET_ASCII_0 + 6)
#define ANM_SCRIPT_ASCII_DEMO_MARKER (ANM_OFFSET_ASCII_0 + 7)
#define ANM_SCRIPT_ASCII_PAUSE_MENU (ANM_OFFSET_ASCII_2 + 0)
#define ANM_SCRIPT_ASCII_RETRY_MENU (ANM_OFFSET_ASCII_2 + 10)
#define ANM_SCRIPT_ASCII_RETRY_MENU_LIVES (ANM_OFFSET_ASCII_2 + 14)

#define ANM_SPRITE_ASCII_LARGE_FONT (ANM_OFFSET_ASCII_0 + 0)
#define ANM_SPRITE_ASCII_SMALL_SCORE (ANM_OFFSET_ASCII_0 + 32)
#define ANM_SPRITE_ASCII_DIGITS (ANM_OFFSET_ASCII_0 + 132)
#define ANM_SPRITE_ASCII_RETRY_MENU_LIVES (ANM_OFFSET_ASCII_1 + 116)
#define ANM_SPRITE_ASCII_LOADING (ANM_OFFSET_ASCII_2 + 14)
#define ANM_SPRITE_ASCII_PAUSE_MENU_DIFFICULTY (ANM_OFFSET_ASCII_2 + 15)

#define ANM_SCRIPT_BULLETS_PELLET (ANM_OFFSET_BULLETS_0 + 0)
#define ANM_SCRIPT_BULLETS_RING_BALL (ANM_OFFSET_BULLETS_0 + 1)
#define ANM_SCRIPT_BULLETS_RICE (ANM_OFFSET_BULLETS_0 + 2)
#define ANM_SCRIPT_BULLETS_BALL (ANM_OFFSET_BULLETS_0 + 3)
#define ANM_SCRIPT_BULLETS_KUNAI (ANM_OFFSET_BULLETS_0 + 4)
#define ANM_SCRIPT_BULLETS_SHARD (ANM_OFFSET_BULLETS_0 + 5)
#define ANM_SCRIPT_BULLETS_ARROWHEAD (ANM_OFFSET_BULLETS_0 + 6)
#define ANM_SCRIPT_BULLETS_BIG_BALL (ANM_OFFSET_BULLETS_0 + 7)
#define ANM_SCRIPT_BULLETS_BUTTERFLY (ANM_OFFSET_BULLETS_0 + 8)
#define ANM_SCRIPT_BULLETS_KNIFE (ANM_OFFSET_BULLETS_0 + 9)
#define ANM_SCRIPT_BULLETS_LASER (ANM_OFFSET_BULLETS_0 + 10)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_SMALL (ANM_OFFSET_BULLETS_0 + 15)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_MEDIUM (ANM_OFFSET_BULLETS_0 + 16)
#define ANM_SCRIPT_BULLETS_SPAWN_DONUT_BIG (ANM_OFFSET_BULLETS_0 + 17)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_FAST (ANM_OFFSET_BULLETS_0 + 18)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_NORMAL (ANM_OFFSET_BULLETS_0 + 19)
#define ANM_SCRIPT_BULLETS_PELLET_SPAWN_SLOW (ANM_OFFSET_BULLETS_0 + 20)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_FAST (ANM_OFFSET_BULLETS_0 + 21)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_NORMAL (ANM_OFFSET_BULLETS_0 + 22)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_SLOW (ANM_OFFSET_BULLETS_0 + 23)
#define ANM_SCRIPT_BULLETS_BIG_BALL_SPAWN_HUGE (ANM_OFFSET_BULLETS_0 + 24)
#define ANM_SCRIPT_BULLETS_BUBBLE (ANM_OFFSET_BULLETS_1 + 0)
#define ANM_SCRIPT_BULLETS_BUBBLE_SPAWN_NORMAL (ANM_OFFSET_BULLETS_1 + 1)
#define ANM_SCRIPT_BULLETS_BUBBLE_SPAWN_SLOW (ANM_OFFSET_BULLETS_1 + 2)
#define ANM_SCRIPT_BULLETS_ENEMY_DEATH_EXPLOSION (ANM_OFFSET_BULLETS_1 + 3)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK1 (ANM_OFFSET_BULLETS_1 + 4)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK2 (ANM_OFFSET_BULLETS_1 + 5)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK3 (ANM_OFFSET_BULLETS_1 + 6)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK4 (ANM_OFFSET_BULLETS_1 + 7)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK5 (ANM_OFFSET_BULLETS_1 + 8)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK6 (ANM_OFFSET_BULLETS_1 + 9)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK7 (ANM_OFFSET_BULLETS_1 + 10)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK8 (ANM_OFFSET_BULLETS_1 + 11)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK9 (ANM_OFFSET_BULLETS_1 + 12)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK10 (ANM_OFFSET_BULLETS_1 + 13)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK11 (ANM_OFFSET_BULLETS_1 + 14)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK12 (ANM_OFFSET_BULLETS_1 + 15)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK13 (ANM_OFFSET_BULLETS_1 + 16)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK14 (ANM_OFFSET_BULLETS_1 + 17)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK15 (ANM_OFFSET_BULLETS_1 + 18)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK16 (ANM_OFFSET_BULLETS_1 + 19)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK17 (ANM_OFFSET_BULLETS_1 + 20)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK18 (ANM_OFFSET_BULLETS_1 + 21)
#define ANM_SCRIPT_BULLETS_FALLING_WEATHER (ANM_OFFSET_BULLETS_1 + 23)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK19 (ANM_OFFSET_BULLETS_1 + 24)
#define ANM_SCRIPT_BULLETS_RANDOM_CHERRY_PETAL (ANM_OFFSET_BULLETS_1 + 25)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK20 (ANM_OFFSET_BULLETS_1 + 26)
#define ANM_SCRIPT_BULLETS_ENEMY_UNK21 (ANM_OFFSET_BULLETS_1 + 27)
#define ANM_SCRIPT_BULLETS_ITEM_SPAWN_ARRAY (ANM_OFFSET_BULLETS_1 + 28)
#define ANM_SCRIPT_BULLETS_ITEM_DESPAWN (ANM_OFFSET_BULLETS_1 + 35)
#define ANM_SCRIPT_BULLETS_SHOW_SPELL_RING (ANM_OFFSET_BULLETS_2 + 0)
#define ANM_SCRIPT_BULLETS_SHOW_BORDER (ANM_OFFSET_BULLETS_3 + 0)

#define ANM_SPRITE_BULLETS_ARROWHEAD (ANM_OFFSET_BULLETS_0 + 96)
#define ANM_SPRITE_BULLETS_ARROWHEAD_WHITE (ANM_OFFSET_BULLETS_0 + 111)
#define ANM_SPRITE_BULLETS_BUTTERFLY (ANM_OFFSET_BULLETS_0 + 120)
#define ANM_SPRITE_BULLETS_BUTTERFLY_LBLUE (ANM_OFFSET_BULLETS_0 + 124)
#define ANM_SPRITE_BULLETS_BUTTERFLY_WHITE (ANM_OFFSET_BULLETS_0 + 127)
#define ANM_SPRITE_BULLETS_ORB (ANM_OFFSET_BULLETS_0 + 146)
#define ANM_SPRITE_BULLETS_ITEMS_OFFSCREEN_ARRAY (ANM_OFFSET_BULLETS_1 + 4)
#define ANM_SPRITE_BULLETS_ITEMS_ARRAY (ANM_OFFSET_BULLETS_1 + 14)
#define ANM_SPRITE_BULLETS_CHERRY_PETAL (ANM_OFFSET_BULLETS_1 + 48)

#define ANM_SCRIPT_EFFECTS_SPELLCARD_BG_ARRAY (ANM_OFFSET_EFFECTS + 0)

#define ANM_SCRIPT_STAGE_BG_SHOW_CRESCENT_ST3 (ANM_OFFSET_STAGE_BG + 4)

#define ANM_SCRIPT_PLAYER_IDLE (ANM_OFFSET_PLAYER + 0)
#define ANM_SCRIPT_PLAYER_MOVING_LEFT (ANM_OFFSET_PLAYER + 1)
#define ANM_SCRIPT_PLAYER_STOPPING_LEFT (ANM_OFFSET_PLAYER + 2)
#define ANM_SCRIPT_PLAYER_MOVING_RIGHT (ANM_OFFSET_PLAYER + 3)
#define ANM_SCRIPT_PLAYER_STOPPING_RIGHT (ANM_OFFSET_PLAYER + 4)
#define ANM_SCRIPT_PLAYER_OPTION_LEFT (ANM_OFFSET_PLAYER + 128)
#define ANM_SCRIPT_PLAYER_OPTION_RIGHT (ANM_OFFSET_PLAYER + 129)
#define ANM_SCRIPT_PLAYER_REIMU_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 133)
#define ANM_SCRIPT_PLAYER_REIMU_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 137)
#define ANM_SCRIPT_PLAYER_REIMU_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 141)
#define ANM_SCRIPT_PLAYER_MARISA_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 5)
#define ANM_SCRIPT_PLAYER_MARISA_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 12)
#define ANM_SCRIPT_PLAYER_MARISA_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 8)
#define ANM_SCRIPT_PLAYER_SAKUYA_A_BOMB_ARRAY (ANM_OFFSET_PLAYER + 5)
#define ANM_SCRIPT_PLAYER_SAKUYA_A_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 7)
#define ANM_SCRIPT_PLAYER_SAKUYA_B_BOMB_ARRAY (ANM_OFFSET_PLAYER + 9)
#define ANM_SCRIPT_PLAYER_SAKUYA_B_FOCUS_BOMB_ARRAY (ANM_OFFSET_PLAYER + 13)

#define ANM_SCRIPT_FACE_PORTRAIT_SHOW_LEFT (ANM_OFFSET_FACE_0 + 0)
#define ANM_SCRIPT_FACE_SPELLCARD_PORTRAIT (ANM_OFFSET_FACE_0 + 1)
#define ANM_SCRIPT_FACE_PORTRAIT_SHOW_RIGHT (ANM_OFFSET_FACE_0 + 2)
#define ANM_SCRIPT_FACE_ENEMY_SPELLCARD_PORTRAIT (ANM_OFFSET_FACE_0 + 3)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_LEFT (ANM_OFFSET_FACE_0 + 4)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_UP (ANM_OFFSET_FACE_0 + 5)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_RIGHT (ANM_OFFSET_FACE_0 + 6)
#define ANM_SCRIPT_FACE_SPELLCARD_DECOR_DOWN (ANM_OFFSET_FACE_0 + 7)

#define ANM_SPRITE_FACE_PORTRAIT_ARRAY (ANM_OFFSET_FACE_0 + 0)
#define ANM_SPRITE_FACE_SPELLCARD_DECOR (ANM_OFFSET_FACE_1 + 4)

#define ANM_SPRITE_FACE_STAGE_ENEMY_PORTRAIT_ARRAY (ANM_OFFSET_FACE_STAGE + 0)
#define ANM_SPRITE_FACE_STAGE_ENEMY_SPELLCARD_PORTRAIT_ARRAY (ANM_OFFSET_FACE_STAGE + 0)

#define ANM_SCRIPT_FRONT_UI_ELEMENTS_ARRAY (ANM_OFFSET_FRONT + 0)

#define ANM_SPRITE_FRONT_ENEMY_NAME_FRAME (ANM_OFFSET_FRONT + 9)
#define ANM_SPRITE_FRONT_ENEMY_NAME (ANM_OFFSET_FRONT + 14)

#define ANM_SCRIPT_LOADING_STAGE_CLEAR_BG (ANM_OFFSET_LOADING + 0)

#define ANM_SCRIPT_TEXT_DIALOGUE (ANM_OFFSET_TEXT + 0)
#define ANM_SCRIPT_TEXT_INTRO (ANM_OFFSET_TEXT + 2)
#define ANM_SCRIPT_TEXT_SPELLCARD_NAME (ANM_OFFSET_TEXT + 4)
#define ANM_SCRIPT_TEXT_ENEMY_SPELLCARD_NAME (ANM_OFFSET_TEXT + 5)
#define ANM_SCRIPT_TEXT_MAINMENU_OPTION_DESC (ANM_OFFSET_TEXT + 6)
#define ANM_SCRIPT_TEXT_MUSIC_DESC (ANM_OFFSET_TEXT + 7)
#define ANM_SCRIPT_TEXT_ENDING (ANM_OFFSET_TEXT + 15)
#define ANM_SCRIPT_TEXT_SPELLCARD_LIST_ARRAY (ANM_OFFSET_TEXT + 21)

#define ANM_SCRIPT_CAPTURE_TRANSITION_SNAPSHOT (ANM_OFFSET_CAPTURE + 1)
#define ANM_SCRIPT_CAPTURE_TRANSITION_QUAD_ARRAY (ANM_OFFSET_CAPTURE + 2)

#define ANM_SCRIPT_STAGE_TEXT (ANM_OFFSET_STAGE_TEXT + 0)
#define ANM_SCRIPT_STAGE_TEXT_MUSIC (ANM_OFFSET_STAGE_TEXT + 4)
#define ANM_SCRIPT_STAGE_TEXT_MUSIC_ST6 (ANM_OFFSET_STAGE_TEXT + 5)

#define ANM_SPRITE_STAGE_TEXT_MUSIC (ANM_OFFSET_STAGE_TEXT + 3)

#define ANM_SCRIPT_MUSIC (ANM_OFFSET_MUSIC_0 + 0)
#define ANM_SCRIPT_MUSIC_TITLE (ANM_OFFSET_MUSIC_1 + 0)

#define ANM_SCRIPT_RESULT_ARRAY (ANM_OFFSET_RESULT_0 + 0)

#define ANM_SPRITE_RESULT_SPELLCARD_BAR (ANM_OFFSET_RESULT_0 + 16)

#define ANM_SCRIPT_ENEMY_ARRAY (ANM_OFFSET_ENEMY + 0)
